spring.application.name=SocailMedia
spring.datasource.url = jdbc:postgresql://localhost:5432/media
spring.datasource.username = postgres
spring.datasource.password = aline123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
